### ISSUE TITLE
IEdgeCollection and IEdgeReference do not use PartitionKey

### ISSUE THREAD

**Issue by Adelzu** [JonasSyrstad/Stardust.Paradox#31]
When traversing through IEdgeCollection<T> or IEdgeReference<T> the query generated does not include the partition key even though it was included in the main Vertex retrieval.

This can accumulate a lot of cost when working with large graphs.

**Comment by JonasSyrstad** [comment]
fixed in v 2.3.2

**Comment by Adelzu** [comment]
IEdgeReference still doesn't respect the partitionKey when setting the Vertex property then saving.
This happens in the queries that create the edge.

**Comment by JonasSyrstad** [comment]
ohh, sorry. forgot to tell you how to enable it..
on your GraphContext class add a type initializer and set the partition key name
static TestContext()
        {
            PartitionKeyName = "pk";
        }
